// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuOgGlOx1HY7exkjyCvS1zBKtD8YAm2Uw',
    appId: '1:389218008252:web:7032b5e193d3ee6a0024b9',
    messagingSenderId: '389218008252',
    projectId: 'taskaya-1',
    authDomain: 'taskaya-1.firebaseapp.com',
    storageBucket: 'taskaya-1.firebasestorage.app',
    measurementId: 'G-CXX8859KH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf0b7ApXkYiXOZLsKbzv329PmwfTZKYpo',
    appId: '1:389218008252:android:fad22089dfca4d9b0024b9',
    messagingSenderId: '389218008252',
    projectId: 'taskaya-1',
    storageBucket: 'taskaya-1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJoMBFVQhMx2MV2mxCdVuEuPDd-bqAYo',
    appId: '1:389218008252:ios:0d8d2bbda0b383240024b9',
    messagingSenderId: '389218008252',
    projectId: 'taskaya-1',
    storageBucket: 'taskaya-1.firebasestorage.app',
    androidClientId: '389218008252-n2a5snhe2tqi2uavqj4dqmmc22aa4bup.apps.googleusercontent.com',
    iosClientId: '389218008252-vg6i0tlkpgmt8i59md4760feq1p5pr3l.apps.googleusercontent.com',
    iosBundleId: 'com.taskaya.taskaya',
  );
}
